# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id$
Configuration parameters:
  url = http://wiki.theborderland.se
  name = theborderland

Please do not commit this to the Git repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'theborderland'
        self.langs = {
            'en': 'wiki.theborderland.se',
        }

        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'en'] = [u'Borderland']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'en'] = [u'Borderland talk']
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'en'] = [u'Image']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'en'] = [u'Image talk']


    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def version(self, code):
        return {
            'en': u'1.24.2',
        }[code]
